project:
  type: website

website:
  title: "LABoratoire pour l'analyse des Interactions, des Réseaux et des INégalités Territoriales"
  site-url: https://tlecorre.gitpages.huma-num.fr/labirint/
    navbar:
    logo: "labirint.png"
    left:
      - menu:
          - href: index.qmd
            text: Accueil
          - href: membres.qmd
            text: Les membres
          - href: projets.qmd
            text: Nos projets
          - href: maitrise.qmd
            text: Faire une maîtrise
          - href: doctorat.qmd
            text: Faire un doctorat
      
    right:
    - icon: fa-gitlab
      href: https://gitlab.huma-num.fr/tlecorre/labirint

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


