
project:
  type: website

website:
  title: "LABoratoire pour l’analyse des Interactions, des Réseaux et des INégalités Territoriales"
  site-url: https://thibaultlecorre.github.io/labirint/

  navbar:
    logo: "fig/logo_lab_udem.png"


    right:
      - icon: fa-github
        href: https://github.com/thibaultlecorre/labirint/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

